version: '2.1'

services:
  app:
    extends:
      file: docker-compose.yml
      service: app
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app
      # When the entire source dir is mounted above, if the host contains a
      # node_modules dir, it will shadow the one in the container. This will
      # happen regardless whether we .dockerignore node_modules. Now, if we want
      # to cancel that shadow, we have to create another shadow, but this time
      # from the container over the host.
      - /usr/src/app/node_modules
